import React, {useMemo, useState} from 'react';
import { createRoot } from 'react-dom/client';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, PieChart, Pie, Cell, LineChart, Line, CartesianGrid } from 'recharts';
import { LayoutDashboard, Users, FileText, Wallet, Package, MessageCircle, ShieldCheck, KanbanSquare, Menu, Search, Plus, Bell, LogOut, ChevronRight, Smartphone, Monitor, CheckCircle2, AlertTriangle, Clock, Settings, UserRound, LockKeyhole, Building2, Send } from 'lucide-react';
import './styles.css';

const services = [
  {id:1, name:'Criação de Sites', category:'Construir', price:1500, monthly:180, desc:'Site responsivo focado em conversão, orçamento e autoridade.'},
  {id:2, name:'Sistemas Sob Medida', category:'Construir', price:4500, monthly:450, desc:'Sistema web para processos, clientes, financeiro e operação.'},
  {id:3, name:'Apps & Plataformas', category:'Construir', price:6500, monthly:650, desc:'Aplicativos e plataformas digitais para celular e web.'},
  {id:4, name:'Automação WhatsApp/Instagram', category:'Automação', price:2500, monthly:300, desc:'Fluxos automáticos, alertas, respostas e integrações.'},
  {id:5, name:'Agentes de IA', category:'Automação', price:3000, monthly:500, desc:'Atendimento, triagem e produtividade com inteligência artificial.'},
  {id:6, name:'Gestão de Tráfego Pago', category:'Crescer', price:900, monthly:900, desc:'Campanhas para captar oportunidades com rastreio.'},
  {id:7, name:'Redes Sociais', category:'Crescer', price:700, monthly:700, desc:'Presença digital, conteúdo e relacionamento.'},
  {id:8, name:'SEO & Conversão', category:'Crescer', price:1200, monthly:350, desc:'Otimização para busca, performance e geração de contatos.'},
  {id:9, name:'Dados, BI & Dashboards', category:'Decidir', price:2800, monthly:500, desc:'Painéis de indicadores, leads, campanhas e financeiro.'},
  {id:10, name:'Cibersegurança', category:'Decidir', price:1800, monthly:400, desc:'Proteção digital, boas práticas e monitoramento.'},
  {id:11, name:'Gerenciamento de Projetos', category:'Operação', price:1600, monthly:350, desc:'Cronograma, responsáveis, prioridades e acompanhamento.'},
  {id:12, name:'Importação de Produtos', category:'Tecnologia', price:2500, monthly:300, desc:'Catálogo, cadastro e controle de produtos.'},
];
const clientsSeed = [
  {id:1, name:'DRM Engenharia', city:'Imperatriz - MA', status:'Ativo', plan:'Nexus Operação', contract:5200, entry:1500, monthly:650, dueDay:10, parcel:'3x', next:'2026-06-10', services:['Sistema','Site','Dashboard'], owner:'Daniel'},
  {id:2, name:'A.L.S.A Neuropsicologia', city:'Imperatriz - MA', status:'Ativo', plan:'Presença Digital', contract:2500, entry:800, monthly:280, dueDay:5, parcel:'2x', next:'2026-06-05', services:['Site','SEO'], owner:'Ana'},
  {id:3, name:'NexCloset', city:'Online', status:'Implantação', plan:'E-commerce', contract:4200, entry:1200, monthly:450, dueDay:15, parcel:'4x', next:'2026-06-15', services:['Sistema','Catálogo','WhatsApp'], owner:'Lucas'},
  {id:4, name:'Galeguinho Lanches', city:'Imperatriz - MA', status:'Atenção', plan:'Marketing Local', contract:1800, entry:500, monthly:700, dueDay:20, parcel:'3x', next:'2026-06-20', services:['Tráfego','Redes Sociais'], owner:'Daniel'},
];
const packagesSeed = [
  {name:'Start Digital', monthly:280, color:'blue', items:['Site institucional','Cadastro de cliente','Suporte básico','Relatórios simples']},
  {name:'Operação Nexus', monthly:650, color:'green', items:['Sistema sob medida','CRM e contratos','Painel financeiro','Automação WhatsApp']},
  {name:'Escala Total', monthly:1200, color:'purple', items:['Marketing + sistema','BI completo','Gestão de tráfego','Acompanhamento estratégico']},
];
const roles = {admin:['dashboard','clientes','contratos','financeiro','produtos','mensagens','projetos','usuarios'], vendedor:['dashboard','clientes','contratos','mensagens'], financeiro:['dashboard','clientes','financeiro','mensagens'], suporte:['dashboard','clientes','projetos','mensagens']};
const nav = [
  ['dashboard','Dashboard',LayoutDashboard],['clientes','Clientes',Users],['contratos','Contratos',FileText],['financeiro','Financeiro',Wallet],['produtos','Produtos/Pacotes',Package],['mensagens','Mensagens',MessageCircle],['projetos','Projetos',KanbanSquare],['usuarios','Usuários e acessos',ShieldCheck]
];
const brl = v => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v);
function App(){
  const [role,setRole]=useState('admin'); const [page,setPage]=useState('dashboard'); const [open,setOpen]=useState(false); const [q,setQ]=useState('');
  const allowed=roles[role]; const clients=clientsSeed.filter(c=>c.name.toLowerCase().includes(q.toLowerCase())||c.plan.toLowerCase().includes(q.toLowerCase()));
  const totals=useMemo(()=>({contracts:clientsSeed.reduce((a,c)=>a+c.contract,0), monthly:clientsSeed.reduce((a,c)=>a+c.monthly,0), receivable:clientsSeed.reduce((a,c)=>a+(c.contract-c.entry),0), active:clientsSeed.filter(c=>c.status==='Ativo').length}),[]);
  const go=p=>{setPage(p);setOpen(false)};
  return <div className="app"><aside className={open?'sidebar show':'sidebar'}><div className="brand"><div className="logo">NX</div><div><b>Nexus Gestão</b><span>Tecnologia LTDA</span></div></div><nav>{nav.filter(n=>allowed.includes(n[0])).map(([id,label,Icon])=><button className={page===id?'active':''} onClick={()=>go(id)} key={id}><Icon size={19}/>{label}</button>)}</nav><div className="sidebarFoot"><span>Perfil atual</span><select value={role} onChange={e=>{setRole(e.target.value);setPage('dashboard')}}>{Object.keys(roles).map(r=><option key={r}>{r}</option>)}</select></div></aside><main><header><button className="iconBtn mobile" onClick={()=>setOpen(!open)}><Menu/></button><div><h1>{nav.find(n=>n[0]===page)?.[1]||'Dashboard'}</h1><p>Sistema interno para clientes, contratos, financeiro e operação.</p></div><div className="topActions"><div className="search"><Search size={18}/><input placeholder="Buscar cliente, pacote..." value={q} onChange={e=>setQ(e.target.value)}/></div><button className="iconBtn"><Bell size={20}/></button><button className="primary"><Plus size={18}/> Novo</button></div></header><section className="content">{page==='dashboard'&&<Dashboard totals={totals}/>} {page==='clientes'&&<Clients clients={clients}/>} {page==='contratos'&&<Contracts/>} {page==='financeiro'&&<Financeiro totals={totals}/>} {page==='produtos'&&<Products/>} {page==='mensagens'&&<Messages/>} {page==='projetos'&&<Projects/>} {page==='usuarios'&&<UsersAccess role={role}/>}</section></main></div>
}
function Stat({label,value,icon:Icon,tone}){return <div className={'card stat '+tone}><div><span>{label}</span><strong>{value}</strong></div><Icon/> </div>}
function Dashboard({totals}){const data=[{m:'Jan',r:3800},{m:'Fev',r:5200},{m:'Mar',r:7400},{m:'Abr',r:6800},{m:'Mai',r:9300},{m:'Jun',r:11200}]; const pie=[{name:'Sistema',value:42},{name:'Marketing',value:31},{name:'Site',value:18},{name:'BI',value:9}]; return <><div className="grid4"><Stat label="Contratos vendidos" value={brl(totals.contracts)} icon={FileText} tone="a"/><Stat label="Receita mensal" value={brl(totals.monthly)} icon={Wallet} tone="b"/><Stat label="A receber" value={brl(totals.receivable)} icon={Clock} tone="c"/><Stat label="Clientes ativos" value={totals.active} icon={Users} tone="d"/></div><div className="grid2"><div className="card"><Title t="Faturamento dos últimos meses"/><ResponsiveContainer height={260}><BarChart data={data}><XAxis dataKey="m"/><YAxis/><Tooltip/><Bar dataKey="r" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></div><div className="card"><Title t="Composição da carteira"/><ResponsiveContainer height={260}><PieChart><Pie data={pie} dataKey="value" nameKey="name" outerRadius={95} label>{pie.map((_,i)=><Cell key={i}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div></div><div className="card"><Title t="Ações prioritárias"/><div className="actionsList"><Action icon={AlertTriangle} title="2 pagamentos vencem esta semana" text="Enviar lembrete via WhatsApp e e-mail automaticamente."/><Action icon={CheckCircle2} title="3 implantações em andamento" text="Acompanhar etapas de briefing, design, desenvolvimento e entrega."/><Action icon={MessageCircle} title="5 clientes sem follow-up recente" text="Criar tarefa para vendedor responsável."/></div></div></>}
function Title({t}){return <div className="title"><h2>{t}</h2><button>Ver tudo <ChevronRight size={16}/></button></div>}
function Action({icon:Icon,title,text}){return <div className="action"><Icon/><div><b>{title}</b><p>{text}</p></div></div>}
function Clients({clients}){return <div className="card"><Title t="Clientes cadastrados"/><div className="table"> <div className="thead"><span>Cliente</span><span>Plano</span><span>Contrato</span><span>Mensalidade</span><span>Status</span></div>{clients.map(c=><div className="row" key={c.id}><span><b>{c.name}</b><small>{c.city}</small></span><span>{c.plan}<small>{c.services.join(', ')}</small></span><span>{brl(c.contract)}<small>Entrada {brl(c.entry)} · {c.parcel}</small></span><span>{brl(c.monthly)}<small>Dia {c.dueDay} · Próx. {c.next}</small></span><span><em className={c.status.toLowerCase()}>{c.status}</em></span></div>)}</div></div>}
function Contracts(){return <div className="grid2"><div className="card"><Title t="Novo contrato"/><Form fields={['Cliente','Serviços contratados','Valor do contrato','Entrada','Quantidade de parcelas','Dia de vencimento','Mensalidade recorrente']}/></div><div className="card"><Title t="Resumo contratual"/><div className="timeline"><Action icon={FileText} title="Cadastro e proposta" text="Dados do cliente, serviços, valor, condições e anexos."/><Action icon={Wallet} title="Implantação parcelada" text="Entrada, parcelas, vencimentos e status de pagamento."/><Action icon={Package} title="Produtos vinculados" text="Sistema, pacote de marketing, BI, automações e adicionais."/></div></div></div>}
function Financeiro({totals}){const data=[{m:'Implantação',v:11800},{m:'Mensalidade',v:2080},{m:'Pendente',v:6200},{m:'Vencido',v:980}]; return <><div className="grid4"><Stat label="Total contratado" value={brl(totals.contracts)} icon={FileText}/><Stat label="MRR" value={brl(totals.monthly)} icon={Wallet}/><Stat label="Pendente" value={brl(6200)} icon={Clock}/><Stat label="Vencido" value={brl(980)} icon={AlertTriangle}/></div><div className="card"><Title t="Visão financeira"/><ResponsiveContainer height={280}><LineChart data={data}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="m"/><YAxis/><Tooltip/><Line type="monotone" dataKey="v" strokeWidth={3}/></LineChart></ResponsiveContainer></div></>}
function Products(){return <><div className="cards3">{packagesSeed.map(p=><div className="card package" key={p.name}><span className="badge">{p.name}</span><h2>{brl(p.monthly)}/mês</h2>{p.items.map(i=><p key={i}><CheckCircle2 size={16}/>{i}</p>)}</div>)}</div><div className="card"><Title t="Catálogo de serviços Nexus"/><div className="serviceGrid">{services.map(s=><div className="service" key={s.id}><b>{s.name}</b><span>{s.category}</span><p>{s.desc}</p><small>Implantação {brl(s.price)} · Mensal {brl(s.monthly)}</small></div>)}</div></div></>}
function Messages(){return <div className="grid2"><div className="card"><Title t="Central de cobrança"/><Form fields={['Cliente','Canal: WhatsApp/E-mail','Modelo de mensagem','Data de envio','Responsável']}/><button className="primary wide"><Send size={18}/> Simular envio</button></div><div className="card"><Title t="Modelos prontos"/><div className="msg"><b>Lembrete antes do vencimento</b><p>Olá, [cliente]! Passando para lembrar que sua mensalidade Nexus vence em [data].</p></div><div className="msg"><b>Cobrança amigável</b><p>Identificamos uma pendência referente ao contrato [contrato]. Podemos ajudar?</p></div></div></div>}
function Projects(){const steps=['Briefing','Design','Desenvolvimento','Revisão','Entrega']; return <div className="kanban">{steps.map((s,i)=><div className="card lane" key={s}><h3>{s}</h3><div className="task"><b>{['DRM Engenharia','A.L.S.A','NexCloset','Galeguinho','Nexus Interno'][i]}</b><p>Responsável definido · prioridade média</p></div></div>)}</div>}
function UsersAccess({role}){return <div className="grid2"><div className="card"><Title t="Perfis de acesso"/><div className="roles">{Object.entries(roles).map(([r,perms])=><div className={r===role?'role selected':'role'} key={r}><UserRound/><b>{r.toUpperCase()}</b><small>{perms.join(', ')}</small></div>)}</div></div><div className="card"><Title t="Segurança"/><Action icon={LockKeyhole} title="Permissões por módulo" text="Cada perfil vê apenas o necessário para sua função."/><Action icon={ShieldCheck} title="Base preparada para autenticação" text="Pronto para integrar JWT, Supabase, Firebase ou API própria."/></div></div>}
function Form({fields}){return <div className="form">{fields.map(f=><label key={f}>{f}<input placeholder={f}/></label>)}</div>}

createRoot(document.getElementById('root')).render(<App/>);
